envVarGroups:
  - name: staging
    envVars:
      - key: DEBUG
        value: true
      - key: ENVIRONMENT
        value: staging

  - name: production
    envVars:
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production

services:
  - type: web
    name: api
    runtime: docker
    region: ohio
    plan: 'free'
    buildCommand: docker build -t api .
    dockerfilePath: ./Dockerfile
