name: Sync Production with Staging

on:
  push:
    branches:
      - production

jobs:
  sync-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging
          path: staging-branch

      - name: Read staging image version
        id: staging-version
        run: |
          STAGING_IMAGE=$(grep -o 'url: docker.io/rctorres/iac-test:.*' staging-branch/render.yaml | cut -d':' -f3-)
          echo "STAGING_IMAGE=${STAGING_IMAGE}" >> $GITHUB_OUTPUT
          rm -rf staging-branch

      - name: Update render.yaml in production
        run: |
          sed -i "s|url: docker.io/rctorres/iac-test:.*|url: docker.io/rctorres/iac-test:${{ steps.staging-version.outputs.STAGING_IMAGE }}|" render.yaml
          cat render.yaml

          git push
