name: Build and Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          echo "VERSION=$(date +'%Y-%m-%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rctorres/iac-test:${{ steps.version.outputs.VERSION }}

      - name: Update render.yaml
        run: |
          sed -i "s|url: rctorres/iac-test:.*|url: rctorres/iac-test:${{ steps.version.outputs.VERSION }}|" render.yaml

      - name: Commit and push render.yaml changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add render.yaml
          git commit -m "Update image version to ${{ steps.version.outputs.VERSION }}"
          git push

      - name: Deploy to Render
        run: |
          curl --request PATCH \
          --url https://api.render.com/v1/blueprints/exs-cu3tao3tq21c73arfjr0 \
          --header 'content-type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
