name: Build and Deploy to Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          echo "VERSION=$(date +'%Y-%m-%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rctorres/iac-test:${{ steps.version.outputs.VERSION }}

      - name: Update render.yaml
        run: |
          sed -i "s|url: docker.io/rctorres/iac-test:.*|url: docker.io/rctorres/iac-test:${{ steps.version.outputs.VERSION }}|" render.yaml
          cat render.yaml

      - name: Push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image version to ${{ steps.version.outputs.VERSION }}"
          file_pattern: 'render.yaml'
